options:
    formatter: stylish
    merge-default-rules: true
files:
    include: '**/*.s+(a|c)ss'
rules:
    no-color-literals: 2
    property-sort-order: 0
    indentation:
        - 2
        -
            size: 4
